// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhfbszihwdedphjnyskr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoZmJzemlod2RlZHBoam55c2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDcxMzUsImV4cCI6MjA2NjQyMzEzNX0.2_4C0_yhHl3PujQp0kSO5n9GcgxMO_lFFBIp1dEMNVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);